import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const MyComponent = ({my_name}) => {

  return (
    <>
      <h1>Hi there, {my_name}</h1>
    </>
  )
}


const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MyComponent
          my_name="Jonny or Fraser"
        />
        <h1></h1>
      </main>
    </div>
  )
}

export default Home;
