"""empty message

Revision ID: 0a076ff8b14a
Revises: faf2ac94c7ab
Create Date: 2023-01-19 18:16:11.046774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a076ff8b14a'
down_revision = 'faf2ac94c7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('desc', sa.String(length=1000), nullable=False),
    sa.Column('time_and_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
