"""empty message

Revision ID: 452a0c841e0f
Revises: 173a110e0f1d
Create Date: 2023-02-07 23:35:01.198388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452a0c841e0f'
down_revision = '173a110e0f1d'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pee')
    # ### end Alembic commands ###
