"""empty message

Revision ID: 66ee5c2061da
Revises: fae76b6d1981
Create Date: 2023-01-10 23:02:38.514305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ee5c2061da'
down_revision = 'fae76b6d1981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('archive')

    # ### end Alembic commands ###
