import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Heading } from "@/components/Heading";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>74 Bully</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <main className="flex min-h-screen flex-col items-center justify-center bg-bully">
        
      </main>
    </>
  );
};

export default Home;
