import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Layout } from "@/layouts/layout";
import Image from "next/image";
import { useRef, useState } from "react";
import type { RefObject } from "react";

const Home: NextPage = () => {
  const audioRefAnni = useRef<HTMLAudioElement>(null);
  const audioRefDog = useRef<HTMLAudioElement>(null);
  const audioRefCat = useRef<HTMLAudioElement>(null);

  const [dog2, setDog2] = useState("/dog2.png");

  const playAudio = (audioRef: RefObject<HTMLAudioElement>) => {
    setDog2("/dog2mouth.png");
    if (audioRef.current) {
      void audioRef.current.play();
    }
    setTimeout(() => {
      setDog2("/dog2.png");
    }
    , 1000);
  };

  
  return (
    <Layout>
      <Head>
        <title>74 Bully</title>
        <meta name="description" content="Generated by Jonny and Fraser" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-row justify-center">
          <Image className="hover:drop-shadow-2xl hover:translate-y-2 hover:cursor-help" src={dog2} alt="Dog" width={200} height={200} onClick={() => playAudio(audioRefAnni)}/>
          <Image className="hover:drop-shadow-2xl hover:translate-y-2 hover:cursor-help" src="/cat.png" alt="Dog" width={200} height={200} onClick={() => playAudio(audioRefCat)}/>
          <Image className="hover:drop-shadow-2xl hover:translate-y-2 hover:cursor-help" src="/dog1.png" alt="Dog" width={200} height={200} onClick={() => playAudio(audioRefDog)}/>
          <audio controls ref={audioRefAnni} className="hidden">
            <source src="/meme-ann.mp3" type="audio/mpeg"/>
          </audio>
          <audio controls ref={audioRefDog} className="hidden">
            <source src="/dog.mp3" type="audio/mpeg"/>
          </audio>
          <audio controls ref={audioRefCat} className="hidden">
            <source src="/meow.mp3" type="audio/mpeg"/>
          </audio>
        </div>
      </div>
    </Layout>
  );
};

export default Home
