on:
  push:
    branches:
      - main
name: 🚀 Deploy API on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.oxtickets.co.uk
        username: bully@74bully.com
        password: ${{ secrets.ftp_password }}
        local-dir: ./backend/